name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/.cache
          key: server-sdk-go

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download Go modules
        run: go mod download

      - name: Mage Build
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: build

      - name: Static Check
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
